CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     TEXT                                    NOT NULL,
    password TEXT                                    NOT NULL,
    role     TEXT                                    NOT NULL,
    email    TEXT,                                -- NOT NULL, -- TODO: open this hint after merge with #10 pull request
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_name UNIQUE (name)
);

CREATE TABLE orders
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    quantity INT4                                    NOT NULL,
    status   TEXT,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_on_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        TEXT                                    NOT NULL,
    description TEXT,
    price       DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uc_products_name UNIQUE (name)
);

CREATE TABLE order_products
(
    order_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_ordpro_on_order_entity FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_ordpro_on_product_entity FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
